#!/bin/sh

# Copyright © 2019 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

if [ $# -ne 1 ]
then
    printf 'Usage: %s EXECUTABLE\n' "$0" >&2
    exit 1
fi
target="$1"

tmux -V > /dev/null

tmpdir=$(mktemp -d -t dochttx.test.XXXXXX)

tmux()
{
    command tmux -f /dev/null -S "$tmpdir/tmux.socket" "$@"
}

tmux new-session -d -- "$target" -d /dev/null
sleep 1
tmux capture-pane -ep
tmux kill-session

rm -rf "$tmpdir"

# vim:ts=4 sts=4 sw=4 et
