dist: trusty
language: c
compiler:
- clang
- gcc
addons:
  apt:
    packages:
    - autoconf
    - autoconf-archive
    - automake
    - cppcheck
    - libncursesw5-dev
    - libzvbi-dev
install:
- python -m pip install --user docutils
script:
- dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
- cppcheck --error-exitcode=1 *.c
- private/autogen
- ./configure --prefix ~/.local || cat config.log /fail
- make
- diff -u
    <(./dochttx --version | head -n1)
    <(IFS=' ()' read name ver _ < doc/changelog; echo "$name $ver")
- private/check-rst
- make install
- cd /
- dochttx --version

# vim:ts=2 sts=2 sw=2 et
