dist: trusty
sudo: false
language: c
compiler:
- clang
- gcc
addons:
  apt:
    packages:
    - autoconf
    - autoconf-archive
    - automake
    - cppcheck
    - libncursesw5-dev
    - libzvbi-dev
install:
- python -m pip install --user docutils
script:
- cppcheck --error-exitcode=1 *.c
- private/autogen
- ./configure --prefix ~/.local
- make
- private/check-rst
- make install
- cd /
- dochttx --version

# vim:ts=2 sts=2 sw=2 et
