.\" Copyright © 2019 Jakub Wilk <jwilk@jwilk.net>
.\" SPDX-License-Identifier: MIT

.TH DOCHTTX 1 2019-02-23 "dochttx 0.3.2" ""
.SH NAME
dochttx \- text mode teletext browser
.SH SYNOPSIS
.SY dochttx
.OP \-d DEVICE
.OP \-l LANG\fR[,\fPLANG\fR\&.\|.\|.\&]
.YS
.SH DESCRIPTION
.B dochttx
is a simple text-mode teletext browser.
.PP
It shows the teletext for the currently running TV channel (tuned by another TV application).
There is no support for channel switching.
.PP
Only analog TV is supported at the moment.
.SH OPTIONS
.TP
.B \-d \fIDEVICE\fP
Use this VBI device.
The default is \fB/dev/vbi0\fP.
.TP
.B \-l \fILANG\fR[,\fILANG\fR\&.\|.\|.\&]
Use character sets appropriate for the selected languages:
.TS
lb l.
ar	Arabic
bg	Bulgarian
cs	Czech
de	German
el	Greek
en	English
es	Spanish
et	Estonian
fi	Finnish
fr	French
he	Hebrew
hr\-Cyrl	Croatian (Cyrillic)
hr\-Latn	Croatian (Latin)
hu	Hungarian
it	Italian
lt	Lithuanian
pl	Polish
pt	Portuguese
ro	Romanian
ru	Russian
sk	Slovak
sl	Slovenian
sr\-Cyrl	Serbian (Cyrillic)
sr\-Latn	Serbian (Latin)
sv	Swedish
tr	Turkish
uk	Ukrainian
.TE
.IP
The default depends on the
.B LC_CTYPE
locale category.
.TP
.BR \-h ", " \-\-help
Show help message and exit.
.TP
.B \-\-version
Show version information and exit.
.SH CONFORMING TO
.UR https://www.etsi.org/\:deliver/\:etsi_en/\:300700_300799/\:300706/\:01.02.01_60/\:en_300706v010201p.pdf
ETSI EN 300 706 V1.2.1 (Enhanced Teletext specification)
.UE
.SH SEE ALSO
.BR locale (7)
