#!/usr/bin/env bash

# Copyright © 2019 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
here=${0%/*}
cd "$here/.."
IFS='()' read _ changelog_version _ < doc/changelog
th=$(grep '^[.]TH' doc/*.1)
[[ $th =~ '"'dochttx' '([0-9.]+) ]]
man_version="${BASH_REMATCH[1]}"
if [[ $changelog_version != $man_version ]]
then
    printf 'changelog version (%s) ≠ man page version (%s)\n' "$changelog_version" "$man_version" >&2
    exit 1
fi
exe_version=$(./dochttx --version)
read _ exe_version _ <<<"$exe_version"
if [[ $changelog_version != $exe_version ]]
then
    printf 'changelog version (%s) ≠ executable version (%s)\n' "$changelog_version" "$exe_version" >&2
    exit 1
fi

# vim:ts=4 sts=4 sw=4 et
