#!/bin/sh
version=${1:?"no version number provided"}
date="$(date -u --rfc-3339=date)"
set -e -x
dch -m -v "$version" -u low -c doc/changelog
export version date
perl -pi -e 's/^AC_INIT[(]\[\S+\], \[\K[0-9.]+/$ENV{version}/' configure.ac
perl -pi -e 's/^([.]TH \S+ 1 )([0-9-]+)( "dochttx )([0-9.]+)/$1$ENV{date}$3$ENV{version}/' doc/*.1
